In [14]:
#for homogenous data only..
#we can create array by following methods
#1> np.array
# np.ones.
#np.arange(1,11,2)
#np.linespace(1,10)
#np.random()
import numpy as np


In [24]:
k = np.array([[3,8,4] , [9,3,5 ], [11,15,19], [19,31,8 ]])
k

array([[ 3,  8,  4],
       [ 9,  3,  5],
       [11, 15, 19],
       [19, 31,  8]])

In [52]:
m = np.array([
                [[4,41],[8,81],[7,71]], 
                [[3,31],[1,5],[5,51]], 
                [[6,61],[9,31],[13,131]]
            ])
m

array([[[  4,  41],
        [  8,  81],
        [  7,  71]],

       [[  3,  31],
        [  1,   5],
        [  5,  51]],

       [[  6,  61],
        [  9,  31],
        [ 13, 131]]])

In [51]:
k[0,2] #subscripting
k[0][1] #indexing
k[0:4:1,-1::1].shape #slicing

(4, 0)

In [82]:
m[1:3:1,1:3:1,0]

m+4
k

array([[ 3, 10,  4],
       [ 9, 20,  5],
       [11, 20, 19],
       [19, 50,  8]])

In [88]:
#k[4:,1] = [10 ,20,20,50]
np.append(k,[[1],[2],[30],[4]],axis=1)


array([[ 3, 10,  4,  1],
       [ 9, 20,  5,  2],
       [11, 20, 19, 30],
       [19, 50,  8,  4]])

In [90]:
np.delete(k,1,axis=1)

array([[ 3,  4],
       [ 9,  5],
       [11, 19],
       [19,  8]])

In [94]:
k.reshape(6,2)
k.dtype

dtype('int32')

In [102]:
a1 = np.array([12.5,6,6])


In [1]:
a1

NameError: name 'a1' is not defined

In [11]:
import seaborn as sb


In [4]:
df= sb.load_dataset("tips")

In [5]:
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [10]:
df.dtypes

total_bill     float64
tip            float64
sex           category
smoker        category
day           category
time          category
size             int64
dtype: object

In [ ]:
df = df.apply(to_numeric=0)

In [9]:
df.corr()


ValueError: could not convert string to float: 'No'

In [12]:
import pandas as pd

matrix = df.corr()
print(matrix)

ValueError: could not convert string to float: 'No'