In [1]:
import numpy as np

In [6]:
np.ones((2,3),dtype=int)
np.zeros((3,3) ,dtype=int)
np.arange(1,11,1)#Gap--for any datatypes 
np.linspace(1,10 , 5)#no of values 
#THe range function only works for intergers not fo any another data types

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [27]:
np.random.seed(10)
np.random.randint(1,6,[2,2])

array([[2, 5],
       [1, 2]])

In [28]:
np.random.rand(3,3)

array([[0.74880388, 0.49850701, 0.22479665],
       [0.19806286, 0.76053071, 0.16911084],
       [0.08833981, 0.68535982, 0.95339335]])

In [35]:
r= np.loadtxt('first.txt',dtype = str)
r

array(['string', ':a', 'str', 'is', 'a', 'imuutable', 'collection', 'of',
       'character'], dtype='<U10')

In [40]:
p = np.random.rand(3,3);
p

array([[0.8052232 , 0.52164715, 0.90864888],
       [0.31923609, 0.09045935, 0.30070006],
       [0.11398436, 0.82868133, 0.04689632]])

In [41]:
a = np.savetxt('new.txt' , p , delimiter=",:,")
a