In [1]:
import numpy as np;



In [3]:
a =np.zeros(10)
a


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
a = np.ones(10)*5
a

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [6]:
np.arange(10 , 51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [7]:
np.arange(10,50,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [12]:
a = np.arange(0,9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [13]:
np.eye(3) #for creatin didentity matirx


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
np.random.rand()

0.2129821892042425

In [16]:
np.random.randn(25)

array([ 0.16670595,  0.07679487,  0.25372762,  1.11965288, -0.90627049,
       -0.42434934,  0.12819423,  0.65774698,  0.57741388,  0.09409873,
        0.88419034,  0.1706709 , -1.99409472, -1.13181093, -1.61331925,
        1.07183695, -0.50545291, -1.94609401,  1.34299174, -0.44668612,
        0.28631922, -2.60364156,  0.29538574,  0.4462231 , -0.04316553])